services:
  - type: web
    name: animal-rescue
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn animal_rescue.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        value: 8y3UjX18Ejly__IAEz4WCkxoWjYTbxRcYPrIsofPvFEWANdRZjIAWqqcMQCxL01ULfI
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: *
      - key: PYTHON_VERSION
        value: 3.12.7

